library = {
    1: {"title": "To Kill a Mockingbird", "author": "Harper Lee", "year": 1960, "type_book": "Fiction", "global_rating": 4.3, "copies": 3, "price": 67.5, "sold": 0},
    2: {"title": "1984", "author": "George Orwell", "year": 1949, "type_book": "Fiction", "global_rating": 4.2, "copies": 2, "price": 45.2, "sold": 0},
    3: {"title": "Pride and Prejudice", "author": "Jane Austen", "year": 1813, "type_book": "Classic", "global_rating": 4.3, "copies": 4, "price": 88.7, "sold": 0},
    4: {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "year": 1925, "type_book": "Fiction", "global_rating": 3.9, "copies": 1, "price": 23.4, "sold": 0},
    5: {"title": "Moby Dick", "author": "Herman Melville", "year": 1851, "type_book": "Classic", "global_rating": 3.5, "copies": 3, "price": 76.8, "sold": 0},
    6: {"title": "War and Peace", "author": "Leo Tolstoy", "year": 1869, "type_book": "Classic", "global_rating": 4.2, "copies": 2, "price": 54.3, "sold": 0},
    7: {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "year": 1951, "type_book": "Fiction", "global_rating": 3.8, "copies": 4, "price": 91.2, "sold": 0},
    8: {"title": "The Hobbit", "author": "J.R.R. Tolkien", "year": 1937, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 1, "price": 12.5, "sold": 0},
    9: {"title": "Fahrenheit 451", "author": "Ray Bradbury", "year": 1953, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.0, "copies": 3, "price": 67.9, "sold": 0},
    10: {"title": "Brave New World", "author": "Aldous Huxley", "year": 1932, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.0, "copies": 2, "price": 45.6, "sold": 0},
    11: {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "year": 1866, "type_book": "Classic", "global_rating": 4.3, "copies": 4, "price": 89.1, "sold": 0},
    12: {"title": "The Odyssey", "author": "Homer", "year": -800, "type_book": "Classic", "global_rating": 3.8, "copies": 1, "price": 15.7, "sold": 0},
    13: {"title": "Jane Eyre", "author": "Charlotte Brontë", "year": 1847, "type_book": "Classic", "global_rating": 4.2, "copies": 3, "price": 72.4, "sold": 0},
    14: {"title": "Wuthering Heights", "author": "Emily Brontë", "year": 1847, "type_book": "Classic", "global_rating": 3.9, "copies": 2, "price": 48.9, "sold": 0},
    15: {"title": "The Divine Comedy", "author": "Dante Alighieri", "year": 1320, "type_book": "Poetry/Drama", "global_rating": 4.0, "copies": 4, "price": 94.3, "sold": 0},
    16: {"title": "Don Quixote", "author": "Miguel de Cervantes", "year": 1605, "type_book": "Classic", "global_rating": 3.9, "copies": 1, "price": 18.2, "sold": 0},
    17: {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "year": 1880, "type_book": "Classic", "global_rating": 4.4, "copies": 3, "price": 75.6, "sold": 0},
    18: {"title": "Anna Karenina", "author": "Leo Tolstoy", "year": 1877, "type_book": "Classic", "global_rating": 4.3, "copies": 2, "price": 52.8, "sold": 0},
    19: {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien", "year": 1954, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.5, "copies": 4, "price": 96.7, "sold": 0},
    20: {"title": "The Alchemist", "author": "Paulo Coelho", "year": 1988, "type_book": "Fiction", "global_rating": 3.9, "copies": 1, "price": 21.3, "sold": 0},
    21: {"title": "The Little Prince", "author": "Antoine de Saint-Exupéry", "year": 1943, "type_book": "Fiction", "global_rating": 4.3, "copies": 3, "price": 68.9, "sold": 0},
    22: {"title": "One Hundred Years of Solitude", "author": "Gabriel García Márquez", "year": 1967, "type_book": "Fiction", "global_rating": 4.1, "copies": 2, "price": 47.5, "sold": 0},
    23: {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "year": 1890, "type_book": "Classic", "global_rating": 4.1, "copies": 4, "price": 92.8, "sold": 0},
    24: {"title": "Frankenstein", "author": "Mary Shelley", "year": 1818, "type_book": "Classic", "global_rating": 3.8, "copies": 1, "price": 14.6, "sold": 0},
    25: {"title": "Dracula", "author": "Bram Stoker", "year": 1897, "type_book": "Horror", "global_rating": 4.0, "copies": 3, "price": 73.2, "sold": 0},
    26: {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas", "year": 1844, "type_book": "Classic", "global_rating": 4.3, "copies": 2, "price": 49.7, "sold": 0},
    27: {"title": "Great Expectations", "author": "Charles Dickens", "year": 1861, "type_book": "Classic", "global_rating": 3.8, "copies": 4, "price": 87.4, "sold": 0},
    28: {"title": "Alice's Adventures in Wonderland", "author": "Lewis Carroll", "year": 1865, "type_book": "Fiction", "global_rating": 4.0, "copies": 1, "price": 16.8, "sold": 0},
    29: {"title": "The Adventures of Huckleberry Finn", "author": "Mark Twain", "year": 1884, "type_book": "Classic", "global_rating": 3.9, "copies": 3, "price": 71.5, "sold": 0},
    30: {"title": "Les Misérables", "author": "Victor Hugo", "year": 1862, "type_book": "Classic", "global_rating": 4.2, "copies": 2, "price": 53.9, "sold": 0},
    31: {"title": "Ulysses", "author": "James Joyce", "year": 1922, "type_book": "Fiction", "global_rating": 3.7, "copies": 4, "price": 95.1, "sold": 0},
    32: {"title": "Madame Bovary", "author": "Gustave Flaubert", "year": 1856, "type_book": "Classic", "global_rating": 3.8, "copies": 1, "price": 19.4, "sold": 0},
    33: {"title": "The Iliad", "author": "Homer", "year": -762, "type_book": "Poetry/Drama", "global_rating": 3.9, "copies": 3, "price": 66.3, "sold": 0},
    34: {"title": "Heart of Darkness", "author": "Joseph Conrad", "year": 1899, "type_book": "Classic", "global_rating": 3.5, "copies": 2, "price": 44.8, "sold": 0},
    35: {"title": "Catch-22", "author": "Joseph Heller", "year": 1961, "type_book": "Fiction", "global_rating": 4.0, "copies": 4, "price": 90.2, "sold": 0},
    36: {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "year": 1969, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.1, "copies": 1, "price": 13.7, "sold": 0},
    37: {"title": "The Stranger", "author": "Albert Camus", "year": 1942, "type_book": "Fiction", "global_rating": 4.0, "copies": 3, "price": 69.4, "sold": 0},
    38: {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "year": 1952, "type_book": "Fiction", "global_rating": 3.8, "copies": 2, "price": 46.1, "sold": 0},
    39: {"title": "A Tale of Two Cities", "author": "Charles Dickens", "year": 1859, "type_book": "Classic", "global_rating": 3.9, "copies": 4, "price": 93.6, "sold": 0},
    40: {"title": "The Bell Jar", "author": "Sylvia Plath", "year": 1963, "type_book": "Fiction", "global_rating": 4.0, "copies": 1, "price": 17.5, "sold": 0},
    41: {"title": "Invisible Man", "author": "Ralph Ellison", "year": 1952, "type_book": "Fiction", "global_rating": 4.1, "copies": 3, "price": 74.8, "sold": 0},
    42: {"title": "Beloved", "author": "Toni Morrison", "year": 1987, "type_book": "Fiction", "global_rating": 3.9, "copies": 2, "price": 51.3, "sold": 0},
    43: {"title": "The Sound and the Fury", "author": "William Faulkner", "year": 1929, "type_book": "Fiction", "global_rating": 3.9, "copies": 4, "price": 88.9, "sold": 0},
    44: {"title": "Lolita", "author": "Vladimir Nabokov", "year": 1955, "type_book": "Fiction", "global_rating": 3.9, "copies": 1, "price": 20.2, "sold": 0},
    45: {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "year": 1926, "type_book": "Fiction", "global_rating": 3.9, "copies": 3, "price": 70.7, "sold": 0},
    46: {"title": "Gone with the Wind", "author": "Margaret Mitchell", "year": 1936, "type_book": "Fiction", "global_rating": 4.3, "copies": 2, "price": 55.4, "sold": 0},
    47: {"title": "The Grapes of Wrath", "author": "John Steinbeck", "year": 1939, "type_book": "Fiction", "global_rating": 4.1, "copies": 4, "price": 97.2, "sold": 0},
    48: {"title": "Of Mice and Men", "author": "John Steinbeck", "year": 1937, "type_book": "Fiction", "global_rating": 3.9, "copies": 1, "price": 22.6, "sold": 0},
    49: {"title": "The Handmaid's Tale", "author": "Margaret Atwood", "year": 1985, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.1, "copies": 3, "price": 65.9, "sold": 0},
    50: {"title": "The Road", "author": "Cormac McCarthy", "year": 2006, "type_book": "Fiction", "global_rating": 3.9, "copies": 2, "price": 43.7, "sold": 0},
    51: {"title": "Dune", "author": "Frank Herbert", "year": 1965, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 4, "price": 91.5, "sold": 0},
    52: {"title": "Foundation", "author": "Isaac Asimov", "year": 1951, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.2, "copies": 1, "price": 14.3, "sold": 0},
    53: {"title": "Neuromancer", "author": "William Gibson", "year": 1984, "type_book": "Fantasy/Sci-Fi", "global_rating": 3.9, "copies": 3, "price": 68.2, "sold": 0},
    54: {"title": "Ender's Game", "author": "Orson Scott Card", "year": 1985, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 2, "price": 47.9, "sold": 0},
    55: {"title": "The Hitchhiker's Guide to the Galaxy", "author": "Douglas Adams", "year": 1979, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.2, "copies": 4, "price": 89.4, "sold": 0},
    56: {"title": "A Brief History of Time", "author": "Stephen Hawking", "year": 1988, "type_book": "Non-Fiction", "global_rating": 4.2, "copies": 1, "price": 18.9, "sold": 0},
    57: {"title": "Sapiens: A Brief History of Humankind", "author": "Yuval Noah Harari", "year": 2011, "type_book": "Non-Fiction", "global_rating": 4.4, "copies": 3, "price": 72.1, "sold": 0},
    58: {"title": "The Selfish Gene", "author": "Richard Dawkins", "year": 1976, "type_book": "Non-Fiction", "global_rating": 4.2, "copies": 2, "price": 50.6, "sold": 0},
    59: {"title": "Silent Spring", "author": "Rachel Carson", "year": 1962, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 4, "price": 94.8, "sold": 0},
    60: {"title": "The Origin of Species", "author": "Charles Darwin", "year": 1859, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 1, "price": 21.8, "sold": 0},
    61: {"title": "A Short History of Nearly Everything", "author": "Bill Bryson", "year": 2003, "type_book": "Non-Fiction", "global_rating": 4.2, "copies": 3, "price": 67.3, "sold": 0},
    62: {"title": "The Double Helix", "author": "James Watson", "year": 1968, "type_book": "Non-Fiction", "global_rating": 3.9, "copies": 2, "price": 45.9, "sold": 0},
    63: {"title": "Guns, Germs, and Steel", "author": "Jared Diamond", "year": 1997, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 4, "price": 92.1, "sold": 0},
    64: {"title": "The Art of War", "author": "Sun Tzu", "year": -500, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 1, "price": 19.7, "sold": 0},
    65: {"title": "The Prince", "author": "Niccolò Machiavelli", "year": 1532, "type_book": "Non-Fiction", "global_rating": 3.8, "copies": 3, "price": 73.6, "sold": 0},
    66: {"title": "Meditations", "author": "Marcus Aurelius", "year": 180, "type_book": "Non-Fiction", "global_rating": 4.3, "copies": 2, "price": 52.2, "sold": 0},
    67: {"title": "Thus Spoke Zarathustra", "author": "Friedrich Nietzsche", "year": 1883, "type_book": "Non-Fiction", "global_rating": 3.9, "copies": 4, "price": 86.7, "sold": 0},
    68: {"title": "Critique of Pure Reason", "author": "Immanuel Kant", "year": 1781, "type_book": "Non-Fiction", "global_rating": 3.8, "copies": 1, "price": 16.4, "sold": 0},
    69: {"title": "Republic", "author": "Plato", "year": -380, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 3, "price": 71.9, "sold": 0},
    70: {"title": "The Wealth of Nations", "author": "Adam Smith", "year": 1776, "type_book": "Non-Fiction", "global_rating": 3.9, "copies": 2, "price": 48.5, "sold": 0},
    71: {"title": "Capital", "author": "Karl Marx", "year": 1867, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 4, "price": 93.2, "sold": 0},
    72: {"title": "The General Theory of Employment, Interest and Money", "author": "John Maynard Keynes", "year": 1936, "type_book": "Non-Fiction", "global_rating": 3.8, "copies": 1, "price": 22.1, "sold": 0},
    73: {"title": "Freakonomics", "author": "Steven Levitt, Stephen Dubner", "year": 2005, "type_book": "Non-Fiction", "global_rating": 4.0, "copies": 3, "price": 69.8, "sold": 0},
    74: {"title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "year": 2011, "type_book": "Non-Fiction", "global_rating": 4.2, "copies": 2, "price": 54.7, "sold": 0},
    75: {"title": "The Power of Habit", "author": "Charles Duhigg", "year": 2012, "type_book": "Self-Help", "global_rating": 4.1, "copies": 4, "price": 90.6, "sold": 0},
    76: {"title": "Atomic Habits", "author": "James Clear", "year": 2018, "type_book": "Self-Help", "global_rating": 4.4, "copies": 1, "price": 13.9, "sold": 0},
    77: {"title": "The 7 Habits of Highly Effective People", "author": "Stephen Covey", "year": 1989, "type_book": "Self-Help", "global_rating": 4.2, "copies": 3, "price": 75.4, "sold": 0},
    78: {"title": "How to Win Friends and Influence People", "author": "Dale Carnegie", "year": 1936, "type_book": "Self-Help", "global_rating": 4.2, "copies": 2, "price": 49.8, "sold": 0},
    79: {"title": "Man's Search for Meaning", "author": "Viktor Frankl", "year": 1946, "type_book": "Non-Fiction", "global_rating": 4.4, "copies": 4, "price": 88.3, "sold": 0},
    80: {"title": "The Subtle Art of Not Giving a F*ck", "author": "Mark Manson", "year": 2016, "type_book": "Self-Help", "global_rating": 3.9, "copies": 1, "price": 20.5, "sold": 0},
    81: {"title": "The Da Vinci Code", "author": "Dan Brown", "year": 2003, "type_book": "Mystery/Thriller", "global_rating": 3.9, "copies": 3, "price": 66.8, "sold": 0},
    82: {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "year": 2005, "type_book": "Mystery/Thriller", "global_rating": 4.1, "copies": 2, "price": 46.4, "sold": 0},
    83: {"title": "Gone Girl", "author": "Gillian Flynn", "year": 2012, "type_book": "Mystery/Thriller", "global_rating": 4.1, "copies": 4, "price": 91.7, "sold": 0},
    84: {"title": "The Silent Patient", "author": "Alex Michaelides", "year": 2019, "type_book": "Mystery/Thriller", "global_rating": 4.2, "copies": 1, "price": 17.3, "sold": 0},
    85: {"title": "And Then There Were None", "author": "Agatha Christie", "year": 1939, "type_book": "Mystery/Thriller", "global_rating": 4.3, "copies": 3, "price": 74.1, "sold": 0},
    86: {"title": "Murder on the Orient Express", "author": "Agatha Christie", "year": 1934, "type_book": "Mystery/Thriller", "global_rating": 4.2, "copies": 2, "price": 53.6, "sold": 0},
    87: {"title": "The Hound of the Baskervilles", "author": "Arthur Conan Doyle", "year": 1902, "type_book": "Mystery/Thriller", "global_rating": 4.1, "copies": 4, "price": 89.9, "sold": 0},
    88: {"title": "Sherlock Holmes: A Study in Scarlet", "author": "Arthur Conan Doyle", "year": 1887, "type_book": "Mystery/Thriller", "global_rating": 4.2, "copies": 1, "price": 21.9, "sold": 0},
    89: {"title": "The Shining", "author": "Stephen King", "year": 1977, "type_book": "Horror", "global_rating": 4.2, "copies": 3, "price": 70.3, "sold": 0},
    90: {"title": "It", "author": "Stephen King", "year": 1986, "type_book": "Horror", "global_rating": 4.2, "copies": 2, "price": 47.2, "sold": 0},
    91: {"title": "Pet Sematary", "author": "Stephen King", "year": 1983, "type_book": "Horror", "global_rating": 4.0, "copies": 4, "price": 92.5, "sold": 0},
    92: {"title": "Carrie", "author": "Stephen King", "year": 1974, "type_book": "Horror", "global_rating": 4.0, "copies": 1, "price": 19.1, "sold": 0},
    93: {"title": "Misery", "author": "Stephen King", "year": 1987, "type_book": "Horror", "global_rating": 4.2, "copies": 3, "price": 76.7, "sold": 0},
    94: {"title": "The Stand", "author": "Stephen King", "year": 1978, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 2, "price": 51.4, "sold": 0},
    95: {"title": "The Name of the Rose", "author": "Umberto Eco", "year": 1980, "type_book": "Mystery/Thriller", "global_rating": 4.1, "copies": 4, "price": 87.6, "sold": 0},
    96: {"title": "The Shadow of the Wind", "author": "Carlos Ruiz Zafón", "year": 2001, "type_book": "Fiction", "global_rating": 4.2, "copies": 1, "price": 15.8, "sold": 0},
    97: {"title": "Life of Pi", "author": "Yann Martel", "year": 2001, "type_book": "Fiction", "global_rating": 3.9, "copies": 3, "price": 72.9, "sold": 0},
    98: {"title": "The Book Thief", "author": "Markus Zusak", "year": 2005, "type_book": "Fiction", "global_rating": 4.4, "copies": 2, "price": 50.1, "sold": 0},
    99: {"title": "The Kite Runner", "author": "Khaled Hosseini", "year": 2003, "type_book": "Fiction", "global_rating": 4.3, "copies": 4, "price": 94.2, "sold": 0},
    100: {"title": "A Thousand Splendid Suns", "author": "Khaled Hosseini", "year": 2007, "type_book": "Fiction", "global_rating": 4.4, "copies": 1, "price": 23.7, "sold": 0},
    101: {"title": "Norwegian Wood", "author": "Haruki Murakami", "year": 1987, "type_book": "Fiction", "global_rating": 4.0, "copies": 3, "price": 68.5, "sold": 0},
    102: {"title": "Kafka on the Shore", "author": "Haruki Murakami", "year": 2002, "type_book": "Fiction", "global_rating": 4.1, "copies": 2, "price": 44.9, "sold": 0},
    103: {"title": "1Q84", "author": "Haruki Murakami", "year": 2009, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.0, "copies": 4, "price": 90.8, "sold": 0},
    104: {"title": "The Wind-Up Bird Chronicle", "author": "Haruki Murakami", "year": 1994, "type_book": "Fiction", "global_rating": 4.1, "copies": 1, "price": 18.6, "sold": 0},
    105: {"title": "Never Let Me Go", "author": "Kazuo Ishiguro", "year": 2005, "type_book": "Fantasy/Sci-Fi", "global_rating": 3.9, "copies": 3, "price": 73.8, "sold": 0},
    106: {"title": "The Remains of the Day", "author": "Kazuo Ishiguro", "year": 1989, "type_book": "Fiction", "global_rating": 4.1, "copies": 2, "price": 52.7, "sold": 0},
    107: {"title": "White Teeth", "author": "Zadie Smith", "year": 2000, "type_book": "Fiction", "global_rating": 3.9, "copies": 4, "price": 88.1, "sold": 0},
    108: {"title": "Midnight's Children", "author": "Salman Rushdie", "year": 1981, "type_book": "Fiction", "global_rating": 4.0, "copies": 1, "price": 20.8, "sold": 0},
    109: {"title": "The Satanic Verses", "author": "Salman Rushdie", "year": 1988, "type_book": "Fiction", "global_rating": 3.8, "copies": 3, "price": 71.2, "sold": 0},
    110: {"title": "The God of Small Things", "author": "Arundhati Roy", "year": 1997, "type_book": "Fiction", "global_rating": 3.9, "copies": 2, "price": 48.3, "sold": 0},
    111: {"title": "The White Tiger", "author": "Aravind Adiga", "year": 2008, "type_book": "Fiction", "global_rating": 3.9, "copies": 4, "price": 93.7, "sold": 0},
    112: {"title": "Wolf Hall", "author": "Hilary Mantel", "year": 2009, "type_book": "Fiction", "global_rating": 4.0, "copies": 1, "price": 16.2, "sold": 0},
    113: {"title": "A Game of Thrones", "author": "George R.R. Martin", "year": 1996, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.5, "copies": 3, "price": 75.9, "sold": 0},
    114: {"title": "Harry Potter and the Philosopher's Stone", "author": "J.K. Rowling", "year": 1997, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.5, "copies": 2, "price": 54.5, "sold": 0},
    115: {"title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling", "year": 1998, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.4, "copies": 4, "price": 89.3, "sold": 0},
    116: {"title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling", "year": 1999, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.6, "copies": 1, "price": 22.4, "sold": 0},
    117: {"title": "Harry Potter and the Goblet of Fire", "author": "J.K. Rowling", "year": 2000, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.5, "copies": 3, "price": 70.1, "sold": 0},
    118: {"title": "Harry Potter and the Order of the Phoenix", "author": "J.K. Rowling", "year": 2003, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.5, "copies": 2, "price": 46.8, "sold": 0},
    119: {"title": "Harry Potter and the Half-Blood Prince", "author": "J.K. Rowling", "year": 2005, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.6, "copies": 4, "price": 91.9, "sold": 0},
    120: {"title": "Harry Potter and the Deathly Hallows", "author": "J.K. Rowling", "year": 2007, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.6, "copies": 1, "price": 19.8, "sold": 0},
    121: {"title": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "author": "C.S. Lewis", "year": 1950, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.2, "copies": 3, "price": 67.1, "sold": 0},
    122: {"title": "The Golden Compass", "author": "Philip Pullman", "year": 1995, "type_book": "Fantasy/Sci-Fi", "global_rating": 3.8, "copies": 2, "price": 45.3, "sold": 0},
    123: {"title": "The Hunger Games", "author": "Suzanne Collins", "year": 2008, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 4, "price": 92.4, "sold": 0},
    124: {"title": "Catching Fire", "author": "Suzanne Collins", "year": 2009, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 1, "price": 21.7, "sold": 0},
    125: {"title": "Mockingjay", "author": "Suzanne Collins", "year": 2010, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.1, "copies": 3, "price": 74.5, "sold": 0},
    126: {"title": "Divergent", "author": "Veronica Roth", "year": 2011, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.2, "copies": 2, "price": 53.2, "sold": 0},
    127: {"title": "The Maze Runner", "author": "James Dashner", "year": 2009, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.0, "copies": 4, "price": 87.8, "sold": 0},
    128: {"title": "The Giver", "author": "Lois Lowry", "year": 1993, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.1, "copies": 1, "price": 17.9, "sold": 0},
    129: {"title": "The Secret History", "author": "Donna Tartt", "year": 1992, "type_book": "Fiction", "global_rating": 4.1, "copies": 3, "price": 69.6, "sold": 0},
    130: {"title": "The Goldfinch", "author": "Donna Tartt", "year": 2013, "type_book": "Fiction", "global_rating": 3.9, "copies": 2, "price": 49.4, "sold": 0},
    131: {"title": "The Night Circus", "author": "Erin Morgenstern", "year": 2011, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.0, "copies": 4, "price": 93.1, "sold": 0},
    132: {"title": "The Starless Sea", "author": "Erin Morgenstern", "year": 2019, "type_book": "Fantasy/Sci-Fi", "global_rating": 3.9, "copies": 1, "price": 20.3, "sold": 0},
    133: {"title": "Circe", "author": "Madeline Miller", "year": 2018, "type_book": "Fantasy/Sci-Fi", "global_rating": 4.3, "copies": 3, "price": 76.3, "sold": 0},
    134: {"title": "The Song of Achilles", "author": "Madeline Miller", "year": 2011, "type_book": "Fiction", "global_rating": 4.3, "copies": 2, "price": 51.8, "sold": 0},
    135: {"title": "Where the Crawdads Sing", "author": "Delia Owens", "year": 2018, "type_book": "Fiction", "global_rating": 4.2, "copies": 4, "price": 88.5, "sold": 0},
    136: {"title": "Educated", "author": "Tara Westover", "year": 2018, "type_book": "Biography/Memoir", "global_rating": 4.5, "copies": 1, "price": 23.1, "sold": 0},
    137: {"title": "Becoming", "author": "Michelle Obama", "year": 2018, "type_book": "Biography/Memoir", "global_rating": 4.5, "copies": 3, "price": 71.4, "sold": 0},
    138: {"title": "Born a Crime", "author": "Trevor Noah", "year": 2016, "type_book": "Biography/Memoir", "global_rating": 4.4, "copies": 2, "price": 47.6, "sold": 0},
    139: {"title": "The Glass Castle", "author": "Jeannette Walls", "year": 2005, "type_book": "Biography/Memoir", "global_rating": 4.3, "copies": 4, "price": 90.3, "sold": 0},
    140: {"title": "Wild", "author": "Cheryl Strayed", "year": 2012, "type_book": "Biography/Memoir", "global_rating": 4.0, "copies": 1, "price": 15.5, "sold": 0},
    141: {"title": "Into the Wild", "author": "Jon Krakauer", "year": 1996, "type_book": "Biography/Memoir", "global_rating": 4.0, "copies": 3, "price": 66.2, "sold": 0},
    142: {"title": "Into Thin Air", "author": "Jon Krakauer", "year": 1997, "type_book": "Biography/Memoir", "global_rating": 4.2, "copies": 2, "price": 44.2, "sold": 0},
    143: {"title": "The Immortal Life of Henrietta Lacks", "author": "Rebecca Skloot", "year": 2010, "type_book": "Biography/Memoir", "global_rating": 4.1, "copies": 4, "price": 91.6, "sold": 0},
    144: {"title": "Unbroken", "author": "Laura Hillenbrand", "year": 2010, "type_book": "Biography/Memoir", "global_rating": 4.4, "copies": 1, "price": 22.9, "sold": 0},
    145: {"title": "The Diary of a Young Girl", "author": "Anne Frank", "year": 1947, "type_book": "Biography/Memoir", "global_rating": 4.2, "copies": 3, "price": 73.7, "sold": 0},
    146: {"title": "Long Walk to Freedom", "author": "Nelson Mandela", "year": 1994, "type_book": "Biography/Memoir", "global_rating": 4.3, "copies": 2, "price": 50.5, "sold": 0},
    147: {"title": "I Know Why the Caged Bird Sings", "author": "Maya Angelou", "year": 1969, "type_book": "Biography/Memoir", "global_rating": 4.3, "copies": 4, "price": 89.2, "sold": 0},
    148: {"title": "The Color Purple", "author": "Alice Walker", "year": 1982, "type_book": "Fiction", "global_rating": 4.2, "copies": 1, "price": 18.4, "sold": 0},
    149: {"title": "Their Eyes Were Watching God", "author": "Zora Neale Hurston", "year": 1937, "type_book": "Fiction", "global_rating": 3.9, "copies": 3, "price": 70.9, "sold": 0},
    150: {"title": "Things Fall Apart", "author": "Chinua Achebe", "year": 1958, "type_book": "Fiction", "global_rating": 3.7, "copies": 2, "price": 46.7, "sold": 0},
    151: {"title": "Bossypants", "author": "Tina Fey", "year": 2011, "type_book": "Comedy", "global_rating": 4.1, "copies": 4, "price": 92.3, "sold": 0},
    152: {"title": "Yes Please", "author": "Amy Poehler", "year": 2014, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 21.5, "sold": 0},
    153: {"title": "Is Everyone Hanging Out Without Me?", "author": "Mindy Kaling", "year": 2011, "type_book": "Comedy", "global_rating": 3.8, "copies": 3, "price": 75.1, "sold": 0},
    154: {"title": "The Hitchhiker's Guide to the Galaxy", "author": "Douglas Adams", "year": 1979, "type_book": "Comedy", "global_rating": 4.2, "copies": 2, "price": 53.8, "sold": 0},
    155: {"title": "Good Omens", "author": "Neil Gaiman & Terry Pratchett", "year": 1990, "type_book": "Comedy", "global_rating": 4.3, "copies": 4, "price": 87.1, "sold": 0},
    156: {"title": "Lamb: The Gospel According to Biff", "author": "Christopher Moore", "year": 2002, "type_book": "Comedy", "global_rating": 4.1, "copies": 1, "price": 19.3, "sold": 0},
    157: {"title": "A Confederacy of Dunces", "author": "John Kennedy Toole", "year": 1980, "type_book": "Comedy", "global_rating": 3.9, "copies": 3, "price": 72.6, "sold": 0},
    158: {"title": "The Princess Bride", "author": "William Goldman", "year": 1973, "type_book": "Comedy", "global_rating": 4.3, "copies": 2, "price": 48.1, "sold": 0},
    159: {"title": "Three Men in a Boat", "author": "Jerome K. Jerome", "year": 1889, "type_book": "Comedy", "global_rating": 4.0, "copies": 4, "price": 93.4, "sold": 0},
    160: {"title": "Catch-22", "author": "Joseph Heller", "year": 1961, "type_book": "Comedy", "global_rating": 4.0, "copies": 1, "price": 16.9, "sold": 0},
    161: {"title": "Bridget Jones's Diary", "author": "Helen Fielding", "year": 1996, "type_book": "Comedy", "global_rating": 3.8, "copies": 3, "price": 68.4, "sold": 0},
    162: {"title": "The Importance of Being Earnest", "author": "Oscar Wilde", "year": 1895, "type_book": "Comedy", "global_rating": 4.2, "copies": 2, "price": 45.7, "sold": 0},
    163: {"title": "The Code of the Woosters", "author": "P.G. Wodehouse", "year": 1938, "type_book": "Comedy", "global_rating": 4.4, "copies": 4, "price": 90.7, "sold": 0},
    164: {"title": "Right Ho, Jeeves", "author": "P.G. Wodehouse", "year": 1934, "type_book": "Comedy", "global_rating": 4.3, "copies": 1, "price": 23.8, "sold": 0},
    165: {"title": "The Thurber Carnival", "author": "James Thurber", "year": 1945, "type_book": "Comedy", "global_rating": 4.0, "copies": 3, "price": 74.2, "sold": 0},
    166: {"title": "Me Talk Pretty One Day", "author": "David Sedaris", "year": 2000, "type_book": "Comedy", "global_rating": 4.1, "copies": 2, "price": 52.4, "sold": 0},
    167: {"title": "Dress Your Family in Corduroy and Denim", "author": "David Sedaris", "year": 2004, "type_book": "Comedy", "global_rating": 4.0, "copies": 4, "price": 88.8, "sold": 0},
    168: {"title": "Calypso", "author": "David Sedaris", "year": 2018, "type_book": "Comedy", "global_rating": 4.2, "copies": 1, "price": 17.6, "sold": 0},
    169: {"title": "Hyperbole and a Half", "author": "Allie Brosh", "year": 2013, "type_book": "Comedy", "global_rating": 4.2, "copies": 3, "price": 71.7, "sold": 0},
    170: {"title": "Solutions and Other Problems", "author": "Allie Brosh", "year": 2020, "type_book": "Comedy", "global_rating": 4.3, "copies": 2, "price": 49.2, "sold": 0},
    171: {"title": "Furiously Happy", "author": "Jenny Lawson", "year": 2015, "type_book": "Comedy", "global_rating": 3.9, "copies": 4, "price": 94.5, "sold": 0},
    172: {"title": "Let's Pretend This Never Happened", "author": "Jenny Lawson", "year": 2012, "type_book": "Comedy", "global_rating": 3.8, "copies": 1, "price": 20.1, "sold": 0},
    173: {"title": "The Areas of My Expertise", "author": "John Hodgman", "year": 2005, "type_book": "Comedy", "global_rating": 3.7, "copies": 3, "price": 66.5, "sold": 0},
    174: {"title": "Vacationland", "author": "John Hodgman", "year": 2017, "type_book": "Comedy", "global_rating": 3.9, "copies": 2, "price": 43.4, "sold": 0},
    175: {"title": "I Feel Bad About My Neck", "author": "Nora Ephron", "year": 2006, "type_book": "Comedy", "global_rating": 3.8, "copies": 4, "price": 89.5, "sold": 0},
    176: {"title": "Heartburn", "author": "Nora Ephron", "year": 1983, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 18.7, "sold": 0},
    177: {"title": "The Rosie Project", "author": "Graeme Simsion", "year": 2013, "type_book": "Comedy", "global_rating": 4.0, "copies": 3, "price": 73.4, "sold": 0},
    178: {"title": "The Rosie Effect", "author": "Graeme Simsion", "year": 2014, "type_book": "Comedy", "global_rating": 3.7, "copies": 2, "price": 50.9, "sold": 0},
    179: {"title": "The Martian", "author": "Andy Weir", "year": 2011, "type_book": "Comedy", "global_rating": 4.4, "copies": 4, "price": 91.3, "sold": 0},
    180: {"title": "The Sellout", "author": "Paul Beatty", "year": 2015, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 22.3, "sold": 0},
    181: {"title": "The 100-Year-Old Man Who Climbed Out the Window", "author": "Jonas Jonasson", "year": 2009, "type_book": "Comedy", "global_rating": 3.9, "copies": 3, "price": 70.4, "sold": 0},
    182: {"title": "The Girl Who Saved the King of Sweden", "author": "Jonas Jonasson", "year": 2013, "type_book": "Comedy", "global_rating": 3.8, "copies": 2, "price": 47.8, "sold": 0},
    183: {"title": "Where'd You Go, Bernadette", "author": "Maria Semple", "year": 2012, "type_book": "Comedy", "global_rating": 3.9, "copies": 4, "price": 92.9, "sold": 0},
    184: {"title": "Today Will Be Different", "author": "Maria Semple", "year": 2016, "type_book": "Comedy", "global_rating": 3.6, "copies": 1, "price": 19.5, "sold": 0},
    185: {"title": "The Help", "author": "Kathryn Stockett", "year": 2009, "type_book": "Comedy", "global_rating": 4.5, "copies": 3, "price": 76.1, "sold": 0},
    186: {"title": "The Guernsey Literary and Potato Peel Pie Society", "author": "Mary Ann Shaffer & Annie Barrows", "year": 2008, "type_book": "Comedy", "global_rating": 4.2, "copies": 2, "price": 54.8, "sold": 0},
    187: {"title": "Eleanor Oliphant Is Completely Fine", "author": "Gail Honeyman", "year": 2017, "type_book": "Comedy", "global_rating": 4.2, "copies": 4, "price": 88.2, "sold": 0},
    188: {"title": "The Unlikely Pilgrimage of Harold Fry", "author": "Rachel Joyce", "year": 2012, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 20.9, "sold": 0},
    189: {"title": "Major Pettigrew's Last Stand", "author": "Helen Simonson", "year": 2010, "type_book": "Comedy", "global_rating": 4.0, "copies": 3, "price": 69.3, "sold": 0},
    190: {"title": "The Storied Life of A.J. Fikry", "author": "Gabrielle Zevin", "year": 2014, "type_book": "Comedy", "global_rating": 4.0, "copies": 2, "price": 46.3, "sold": 0},
    191: {"title": "The Little Paris Bookshop", "author": "Nina George", "year": 2013, "type_book": "Comedy", "global_rating": 3.8, "copies": 4, "price": 93.8, "sold": 0},
    192: {"title": "The Bookshop on the Corner", "author": "Jenny Colgan", "year": 2016, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 17.8, "sold": 0},
    193: {"title": "The Cafe by the Sea", "author": "Jenny Colgan", "year": 2017, "type_book": "Comedy", "global_rating": 3.8, "copies": 3, "price": 72.3, "sold": 0},
    194: {"title": "The Readers of Broken Wheel Recommend", "author": "Katarina Bivald", "year": 2013, "type_book": "Comedy", "global_rating": 3.7, "copies": 2, "price": 49.6, "sold": 0},
    195: {"title": "The Curious Charms of Arthur Pepper", "author": "Phaedra Patrick", "year": 2016, "type_book": "Comedy", "global_rating": 3.8, "copies": 4, "price": 87.3, "sold": 0},
    196: {"title": "The Lido", "author": "Libby Page", "year": 2018, "type_book": "Comedy", "global_rating": 3.9, "copies": 1, "price": 21.6, "sold": 0},
    197: {"title": "The Single Ladies of Jacaranda Retirement Village", "author": "Joanna Nell", "year": 2018, "type_book": "Comedy", "global_rating": 3.8, "copies": 3, "price": 71.1, "sold": 0},
    198: {"title": "The Brilliant Life of Eudora Honeysett", "author": "Annie Lyons", "year": 2020, "type_book": "Comedy", "global_rating": 4.0, "copies": 2, "price": 48.4, "sold": 0},
    199: {"title": "The Switch", "author": "Beth O'Leary", "year": 2020, "type_book": "Comedy", "global_rating": 3.9, "copies": 4, "price": 90.1, "sold": 0},
    200: {"title": "The Flatshare", "author": "Beth O'Leary", "year": 2019, "type_book": "Comedy", "global_rating": 4.1, "copies": 1, "price": 16.1, "sold": 0},
    201: {"title": "The Bourne Identity", "author": "Robert Ludlum", "year": 1980, "type_book": "Action", "global_rating": 4.1, "copies": 3, "price": 70.6, "sold": 0},
    202: {"title": "The Hunt for Red October", "author": "Tom Clancy", "year": 1984, "type_book": "Action", "global_rating": 4.2, "copies": 2, "price": 47.1, "sold": 0},
    203: {"title": "Patriot Games", "author": "Tom Clancy", "year": 1987, "type_book": "Action", "global_rating": 4.1, "copies": 4, "price": 92.6, "sold": 0},
    204: {"title": "Clear and Present Danger", "author": "Tom Clancy", "year": 1989, "type_book": "Action", "global_rating": 4.2, "copies": 1, "price": 19.9, "sold": 0},
    205: {"title": "The Sum of All Fears", "author": "Tom Clancy", "year": 1991, "type_book": "Action", "global_rating": 4.1, "copies": 3, "price": 73.9, "sold": 0},
    206: {"title": "Rainbow Six", "author": "Tom Clancy", "year": 1998, "type_book": "Action", "global_rating": 4.2, "copies": 2, "price": 51.2, "sold": 0},
    207: {"title": "Without Remorse", "author": "Tom Clancy", "year": 1993, "type_book": "Action", "global_rating": 4.3, "copies": 4, "price": 89.8, "sold": 0},
    208: {"title": "The Da Vinci Code", "author": "Dan Brown", "year": 2003, "type_book": "Action", "global_rating": 3.9, "copies": 1, "price": 22.7, "sold": 0},
    209: {"title": "Angels & Demons", "author": "Dan Brown", "year": 2000, "type_book": "Action", "global_rating": 3.9, "copies": 3, "price": 68.6, "sold": 0},
    210: {"title": "Inferno", "author": "Dan Brown", "year": 2013, "type_book": "Action", "global_rating": 3.8, "copies": 2, "price": 44.6, "sold": 0},
    211: {"title": "The Lost Symbol", "author": "Dan Brown", "year": 2009, "type_book": "Action", "global_rating": 3.7, "copies": 4, "price": 91.0, "sold": 0},
    212: {"title": "Origin", "author": "Dan Brown", "year": 2017, "type_book": "Action", "global_rating": 3.8, "copies": 1, "price": 18.0, "sold": 0},
    213: {"title": "The Firm", "author": "John Grisham", "year": 1991, "type_book": "Action", "global_rating": 4.0, "copies": 3, "price": 72.0, "sold": 0},
    214: {"title": "The Pelican Brief", "author": "John Grisham", "year": 1992, "type_book": "Action", "global_rating": 4.0, "copies": 2, "price": 50.3, "sold": 0},
    215: {"title": "The Client", "author": "John Grisham", "year": 1993, "type_book": "Action", "global_rating": 4.0, "copies": 4, "price": 88.4, "sold": 0},
    216: {"title": "The Runaway Jury", "author": "John Grisham", "year": 1996, "type_book": "Action", "global_rating": 4.0, "copies": 1, "price": 21.0, "sold": 0},
    217: {"title": "The Partner", "author": "John Grisham", "year": 1997, "type_book": "Action", "global_rating": 3.9, "copies": 3, "price": 69.0, "sold": 0},
    218: {"title": "The Street Lawyer", "author": "John Grisham", "year": 1998, "type_book": "Action", "global_rating": 3.8, "copies": 2, "price": 46.0, "sold": 0},
    219: {"title": "The Brethren", "author": "John Grisham", "year": 2000, "type_book": "Action", "global_rating": 3.7, "copies": 4, "price": 93.0, "sold": 0},
    220: {"title": "The Summons", "author": "John Grisham", "year": 2002, "type_book": "Action", "global_rating": 3.6, "copies": 1, "price": 19.0, "sold": 0},
    221: {"title": "The King of Torts", "author": "John Grisham", "year": 2003, "type_book": "Action", "global_rating": 3.7, "copies": 3, "price": 70.0, "sold": 0},
    222: {"title": "The Last Juror", "author": "John Grisham", "year": 2004, "type_book": "Action", "global_rating": 3.8, "copies": 2, "price": 48.0, "sold": 0},
    223: {"title": "The Broker", "author": "John Grisham", "year": 2005, "type_book": "Action", "global_rating": 3.6, "copies": 4, "price": 90.0, "sold": 0},
    224: {"title": "The Appeal", "author": "John Grisham", "year": 2008, "type_book": "Action", "global_rating": 3.7, "copies": 1, "price": 20.0, "sold": 0},
    225: {"title": "The Associate", "author": "John Grisham", "year": 2009, "type_book": "Action", "global_rating": 3.5, "copies": 3, "price": 65.0, "sold": 0},
    226: {"title": "The Confession", "author": "John Grisham", "year": 2010, "type_book": "Action", "global_rating": 4.0, "copies": 2, "price": 42.0, "sold": 0},
    227: {"title": "The Litigators", "author": "John Grisham", "year": 2011, "type_book": "Action", "global_rating": 3.7, "copies": 4, "price": 87.0, "sold": 0},
    228: {"title": "The Racketeer", "author": "John Grisham", "year": 2012, "type_book": "Action", "global_rating": 3.7, "copies": 1, "price": 23.0, "sold": 0},
    229: {"title": "Sycamore Row", "author": "John Grisham", "year": 2013, "type_book": "Action", "global_rating": 4.0, "copies": 3, "price": 74.0, "sold": 0},
    230: {"title": "Gray Mountain", "author": "John Grisham", "year": 2014, "type_book": "Action", "global_rating": 3.6, "copies": 2, "price": 52.0, "sold": 0},
    231: {"title": "Rogue Lawyer", "author": "John Grisham", "year": 2015, "type_book": "Action", "global_rating": 3.7, "copies": 4, "price": 89.0, "sold": 0},
    232: {"title": "The Whistler", "author": "John Grisham", "year": 2016, "type_book": "Action", "global_rating": 3.8, "copies": 1, "price": 17.0, "sold": 0},
    233: {"title": "Camino Island", "author": "John Grisham", "year": 2017, "type_book": "Action", "global_rating": 3.6, "copies": 3, "price": 71.0, "sold": 0},
    234: {"title": "The Reckoning", "author": "John Grisham", "year": 2018, "type_book": "Action", "global_rating": 3.7, "copies": 2, "price": 49.0, "sold": 0},
    235: {"title": "The Guardians", "author": "John Grisham", "year": 2019, "type_book": "Action", "global_rating": 4.0, "copies": 4, "price": 86.0, "sold": 0},
    236: {"title": "A Time to Kill", "author": "John Grisham", "year": 1989, "type_book": "Action", "global_rating": 4.2, "copies": 1, "price": 24.0, "sold": 0},
    237: {"title": "The Lincoln Lawyer", "author": "Michael Connelly", "year": 2005, "type_book": "Action", "global_rating": 4.2, "copies": 3, "price": 75.0, "sold": 0},
    238: {"title": "The Brass Verdict", "author": "Michael Connelly", "year": 2008, "type_book": "Action", "global_rating": 4.3, "copies": 2, "price": 55.0, "sold": 0},
    239: {"title": "The Reversal", "author": "Michael Connelly", "year": 2010, "type_book": "Action", "global_rating": 4.2, "copies": 4, "price": 85.0, "sold": 0},
    240: {"title": "The Fifth Witness", "author": "Michael Connelly", "year": 2011, "type_book": "Action", "global_rating": 4.1, "copies": 1, "price": 25.0, "sold": 0},
    241: {"title": "The Gods of Guilt", "author": "Michael Connelly", "year": 2013, "type_book": "Action", "global_rating": 4.2, "copies": 3, "price": 78.0, "sold": 0},
    242: {"title": "The Law of Innocence", "author": "Michael Connelly", "year": 2020, "type_book": "Action", "global_rating": 4.3, "copies": 2, "price": 56.0, "sold": 0},
    243: {"title": "The Black Echo", "author": "Michael Connelly", "year": 1992, "type_book": "Action", "global_rating": 4.1, "copies": 4, "price": 84.0, "sold": 0},
    244: {"title": "The Black Ice", "author": "Michael Connelly", "year": 1993, "type_book": "Action", "global_rating": 4.0, "copies": 1, "price": 26.0, "sold": 0},
    245: {"title": "The Concrete Blonde", "author": "Michael Connelly", "year": 1994, "type_book": "Action", "global_rating": 4.2, "copies": 3, "price": 77.0, "sold": 0},
    246: {"title": "The Last Coyote", "author": "Michael Connelly", "year": 1995, "type_book": "Action", "global_rating": 4.1, "copies": 2, "price": 57.0, "sold": 0},
    247: {"title": "Trunk Music", "author": "Michael Connelly", "year": 1997, "type_book": "Action", "global_rating": 4.0, "copies": 4, "price": 83.0, "sold": 0},
    248: {"title": "Angels Flight", "author": "Michael Connelly", "year": 1999, "type_book": "Action", "global_rating": 4.1, "copies": 1, "price": 27.0, "sold": 0},
    249: {"title": "A Darkness More Than Night", "author": "Michael Connelly", "year": 2001, "type_book": "Action", "global_rating": 4.2, "copies": 3, "price": 76.0, "sold": 0},
    250: {"title": "City of Bones", "author": "Michael Connelly", "year": 2002, "type_book": "Action", "global_rating": 4.1, "copies": 2, "price": 58.0, "sold": 0},
    251: {"title": "The Exorcist", "author": "William Peter Blatty", "year": 1971, "type_book": "Horror", "global_rating": 4.2, "copies": 4, "price": 82.0, "sold": 0},
    252: {"title": "Rosemary's Baby", "author": "Ira Levin", "year": 1967, "type_book": "Horror", "global_rating": 4.1, "copies": 1, "price": 28.0, "sold": 0},
    253: {"title": "The Haunting of Hill House", "author": "Shirley Jackson", "year": 1959, "type_book": "Horror", "global_rating": 4.0, "copies": 3, "price": 79.0, "sold": 0},
    254: {"title": "We Have Always Lived in the Castle", "author": "Shirley Jackson", "year": 1962, "type_book": "Horror", "global_rating": 4.0, "copies": 2, "price": 59.0, "sold": 0},
    255: {"title": "The Silence of the Lambs", "author": "Thomas Harris", "year": 1988, "type_book": "Horror", "global_rating": 4.2, "copies": 4, "price": 81.0, "sold": 0},
    256: {"title": "Red Dragon", "author": "Thomas Harris", "year": 1981, "type_book": "Horror", "global_rating": 4.1, "copies": 1, "price": 29.0, "sold": 0},
    257: {"title": "Hannibal", "author": "Thomas Harris", "year": 1999, "type_book": "Horror", "global_rating": 3.8, "copies": 3, "price": 80.0, "sold": 0},
    258: {"title": "Hannibal Rising", "author": "Thomas Harris", "year": 2006, "type_book": "Horror", "global_rating": 3.4, "copies": 2, "price": 60.0, "sold": 0},
    259: {"title": "The Girl Next Door", "author": "Jack Ketchum", "year": 1989, "type_book": "Horror", "global_rating": 3.9, "copies": 4, "price": 79.5, "sold": 0},
    260: {"title": "Off Season", "author": "Jack Ketchum", "year": 1980, "type_book": "Horror", "global_rating": 3.8, "copies": 1, "price": 30.0, "sold": 0},
    261: {"title": "The Woman", "author": "Jack Ketchum", "year": 2010, "type_book": "Horror", "global_rating": 3.7, "copies": 3, "price": 78.5, "sold": 0},
    262: {"title": "Bird Box", "author": "Josh Malerman", "year": 2014, "type_book": "Horror", "global_rating": 4.0, "copies": 2, "price": 61.0, "sold": 0},
    263: {"title": "Malorie", "author": "Josh Malerman", "year": 2020, "type_book": "Horror", "global_rating": 3.7, "copies": 4, "price": 78.0, "sold": 0},
    264: {"title": "House of Leaves", "author": "Mark Z. Danielewski", "year": 2000, "type_book": "Horror", "global_rating": 4.1, "copies": 1, "price": 31.0, "sold": 0},
    265: {"title": "The Only Good Indians", "author": "Stephen Graham Jones", "year": 2020, "type_book": "Horror", "global_rating": 3.9, "copies": 3, "price": 77.5, "sold": 0},
    266: {"title": "My Heart Is a Chainsaw", "author": "Stephen Graham Jones", "year": 2021, "type_book": "Horror", "global_rating": 3.8, "copies": 2, "price": 62.0, "sold": 0},
    267: {"title": "The Terror", "author": "Dan Simmons", "year": 2007, "type_book": "Horror", "global_rating": 4.1, "copies": 4, "price": 76.5, "sold": 0},
    268: {"title": "Carrion Comfort", "author": "Dan Simmons", "year": 1989, "type_book": "Horror", "global_rating": 4.0, "copies": 1, "price": 32.0, "sold": 0},
    269: {"title": "Summer of Night", "author": "Dan Simmons", "year": 1991, "type_book": "Horror", "global_rating": 4.0, "copies": 3, "price": 75.5, "sold": 0},
    270: {"title": "A Head Full of Ghosts", "author": "Paul Tremblay", "year": 2015, "type_book": "Horror", "global_rating": 3.8, "copies": 2, "price": 63.0, "sold": 0},
    271: {"title": "The Cabin at the End of the World", "author": "Paul Tremblay", "year": 2018, "type_book": "Horror", "global_rating": 3.7, "copies": 4, "price": 75.0, "sold": 0},
    272: {"title": "Disappearance at Devil's Rock", "author": "Paul Tremblay", "year": 2016, "type_book": "Horror", "global_rating": 3.6, "copies": 1, "price": 33.0, "sold": 0},
    273: {"title": "The Ruins", "author": "Scott Smith", "year": 2006, "type_book": "Horror", "global_rating": 3.8, "copies": 3, "price": 74.5, "sold": 0},
    274: {"title": "A Simple Plan", "author": "Scott Smith", "year": 1993, "type_book": "Horror", "global_rating": 4.0, "copies": 2, "price": 64.0, "sold": 0},
    275: {"title": "Heart-Shaped Box", "author": "Joe Hill", "year": 2007, "type_book": "Horror", "global_rating": 3.9, "copies": 4, "price": 74.0, "sold": 0},
    276: {"title": "NOS4A2", "author": "Joe Hill", "year": 2013, "type_book": "Horror", "global_rating": 4.1, "copies": 1, "price": 34.0, "sold": 0},
    277: {"title": "The Fireman", "author": "Joe Hill", "year": 2016, "type_book": "Horror", "global_rating": 3.9, "copies": 3, "price": 73.5, "sold": 0},
    278: {"title": "Horns", "author": "Joe Hill", "year": 2010, "type_book": "Horror", "global_rating": 3.9, "copies": 2, "price": 65.0, "sold": 0},
    279: {"title": "Strange Weather", "author": "Joe Hill", "year": 2017, "type_book": "Horror", "global_rating": 3.8, "copies": 4, "price": 73.0, "sold": 0},
    280: {"title": "The Troop", "author": "Nick Cutter", "year": 2014, "type_book": "Horror", "global_rating": 3.9, "copies": 1, "price": 35.0, "sold": 0},
    281: {"title": "The Deep", "author": "Nick Cutter", "year": 2015, "type_book": "Horror", "global_rating": 3.7, "copies": 3, "price": 72.5, "sold": 0},
    282: {"title": "Little Heaven", "author": "Nick Cutter", "year": 2016, "type_book": "Horror", "global_rating": 3.6, "copies": 2, "price": 66.0, "sold": 0},
    283: {"title": "The Breach", "author": "Nick Cutter", "year": 2020, "type_book": "Horror", "global_rating": 3.8, "copies": 4, "price": 72.0, "sold": 0},
    284: {"title": "The Ritual", "author": "Adam Nevill", "year": 2011, "type_book": "Horror", "global_rating": 3.8, "copies": 1, "price": 36.0, "sold": 0},
    285: {"title": "Last Days", "author": "Adam Nevill", "year": 2012, "type_book": "Horror", "global_rating": 3.9, "copies": 3, "price": 71.5, "sold": 0},
    286: {"title": "No One Gets Out Alive", "author": "Adam Nevill", "year": 2014, "type_book": "Horror", "global_rating": 3.8, "copies": 2, "price": 67.0, "sold": 0},
    287: {"title": "Under a Watchful Eye", "author": "Adam Nevill", "year": 2017, "type_book": "Horror", "global_rating": 3.7, "copies": 4, "price": 71.0, "sold": 0},
    288: {"title": "The Reddening", "author": "Adam Nevill", "year": 2019, "type_book": "Horror", "global_rating": 3.8, "copies": 1, "price": 37.0, "sold": 0},
    289: {"title": "Cunning Folk", "author": "Adam Nevill", "year": 2021, "type_book": "Horror", "global_rating": 3.9, "copies": 3, "price": 70.5, "sold": 0},
    290: {"title": "The Twisted Ones", "author": "T. Kingfisher", "year": 2019, "type_book": "Horror", "global_rating": 3.8, "copies": 2, "price": 68.0, "sold": 0},
    291: {"title": "The Hollow Places", "author": "T. Kingfisher", "year": 2020, "type_book": "Horror", "global_rating": 3.9, "copies": 4, "price": 70.0, "sold": 0},
    292: {"title": "What Moves the Dead", "author": "T. Kingfisher", "year": 2022, "type_book": "Horror", "global_rating": 4.0, "copies": 1, "price": 38.0, "sold": 0},
    293: {"title": "The Luminous Dead", "author": "Caitlin Starling", "year": 2019, "type_book": "Horror", "global_rating": 3.7, "copies": 3, "price": 69.5, "sold": 0},
    294: {"title": "The Death of Jane Lawrence", "author": "Caitlin Starling", "year": 2021, "type_book": "Horror", "global_rating": 3.6, "copies": 2, "price": 69.0, "sold": 0}
}
current_id = 295